name: Build Test Release

on:
  push:
    tags:
      - '**'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f test_reqs.txt ]; then pip install -r test_reqs.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python setup.py install
      - name: Test with pytest
        run:
          make test
      - name: release
        uses: pypa/gh-action-pypi-publish@master
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}